info:
  contact: {}
paths:
  /:
    get:
      description: returns `Hello World`
      responses:
        "200":
          description: OK
      summary: Hello World Route
      tags:
      - default
  /auth/self:
    get:
      description: Returns the authenticated user
      responses:
        "200":
          description: OK
      summary: Get Authenticated User
      tags:
      - auth
  /health:
    get:
      description: get the database health
      responses:
        "200":
          description: OK
      summary: Returns the database health
      tags:
      - default
  /register:
    post:
      description: Register a new user
      responses:
        "200":
          description: OK
      summary: Register Route
      tags:
      - auth
swagger: "2.0"
