definitions:
  models.NewVehiclePostData:
    properties:
      description:
        type: string
      images:
        items:
          type: string
        type: array
      model:
        type: string
      nickname:
        type: string
      registration:
        type: string
    type: object
  models.Token:
    properties:
      token:
        type: string
    type: object
  models.UpdateSelf:
    properties:
      avatar:
        type: string
      bio:
        type: string
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      public:
        type: boolean
      username:
        type: string
    type: object
  models.User:
    properties:
      avatar:
        type: string
      bio:
        type: string
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      public:
        type: boolean
      username:
        type: string
    type: object
  models.Username:
    properties:
      username:
        type: string
    type: object
  models.Vehicle:
    properties:
      color:
        type: string
      description:
        type: string
      engine_size:
        type: integer
      id:
        type: string
      images:
        items:
          type: string
        type: array
      insurance_date:
        type: string
      make:
        type: string
      model:
        type: string
      mot_date:
        type: string
      nickname:
        type: string
      registered:
        type: string
      registration:
        type: string
      service_date:
        type: string
      tax_date:
        type: string
      user_id:
        type: string
      year:
        type: integer
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: returns `Hello World`
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Hello World Route
      tags:
      - default
  /auth/self:
    get:
      description: Returns the authenticated user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Get Authenticated User
      tags:
      - self
    post:
      description: Creates a new user
      parameters:
      - description: update params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateSelf'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Add New Authenticated User
      tags:
      - self
    put:
      description: updates the authenticated user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Updates the Authenticated User
      tags:
      - self
  /auth/users:
    get:
      description: Returns a list of all users
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Get All Users
      tags:
      - user
  /auth/users/:id:
    get:
      description: Returns a user object
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Get a User by ID
      tags:
      - user
  /auth/utils/username:
    post:
      description: Checks if a username is available
      parameters:
      - description: username param
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Username'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Is a Username Available
      tags:
      - utils
  /auth/vehicles:
    get:
      description: returns a list of vehicles for the authenticated user
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Vehicle'
            type: array
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Gets the vehicles for the authenticated user
      tags:
      - vehicles
    post:
      description: adds a vehicle to a user's account
      parameters:
      - description: vehicle params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.NewVehiclePostData'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Add a user's vehicle
      tags:
      - vehicles
  /auth/vehicles/:id:
    get:
      description: returns a vehicle object requested by ID
      parameters:
      - description: Vehicle ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Vehicle'
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Gets a vehicle by ID
      tags:
      - vehicles
  /auth/vehicles/registration/:reg:
    get:
      description: returns a vehicle object requested by registration
      parameters:
      - description: Registration
        in: path
        name: reg
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Vehicle'
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Gets the authenticated user's vehicle by registration
      tags:
      - vehicles
  /health:
    get:
      description: get the database health
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Returns the database health
      tags:
      - default
  /login:
    post:
      description: Logs in a user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Token'
      summary: Login Route
      tags:
      - auth
  /register:
    post:
      description: Register a new user
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Register Route
      tags:
      - auth
swagger: "2.0"
