info:
  contact: {}
paths:
  /:
    get:
      description: returns `Hello World`
      responses:
        "200":
          description: OK
      summary: Hello World Route
      tags:
      - default
  /auth/login:
    post:
      description: Login a user
      responses:
        "200":
          description: OK
      summary: Login Route
      tags:
      - auth
  /auth/register:
    post:
      description: Register a new user
      responses:
        "200":
          description: OK
      summary: Register Route
      tags:
      - auth
  /health:
    get:
      description: get the database health
      responses:
        "200":
          description: OK
      summary: Returns the database health
      tags:
      - default
swagger: "2.0"
