definitions:
  models.SelfUser:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  models.Token:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: returns `Hello World`
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Hello World Route
      tags:
      - default
  /auth/self:
    get:
      description: Returns the authenticated user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SelfUser'
      summary: Get Authenticated User
      tags:
      - user
  /auth/users:
    get:
      description: Returns a list of all users
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SelfUser'
            type: array
      summary: Get All Users
      tags:
      - user
  /health:
    get:
      description: get the database health
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Returns the database health
      tags:
      - default
  /login:
    post:
      description: Logs in a user
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Token'
      summary: Login Route
      tags:
      - auth
  /register:
    post:
      description: Register a new user
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Register Route
      tags:
      - auth
swagger: "2.0"
